#!/usr/bin/env zsh

selected=$(find $HOME/personal/ -mindepth 1 -maxdepth 1 -type d | fzf)

if [[ -z $selected ]]; then
            exit 0
fi

selected_name=$(basename "$selected" | tr . _)
tmux_running=$(pgrep tmux)

if [[ -z $TMUX ]] && [[ -z $tmux_running ]]; then
        tmux new-session -ds $selected_name -c $selected
        tmux new-window -t $selected_name -c $selected
        tmux new-window -t $selected_name -c $selected
        tmux send-keys -t $selected_name:1 'nvim .' Enter
        tmux send-keys -t $selected_name:3 'opencode' Enter
        tmux select-window -t $selected_name:1
        tmux attach-session -t $selected_name
        exit 0
fi

if ! tmux has-session -t $selected_name 2> /dev/null; then
        tmux new-session -ds $selected_name -c $selected
        tmux new-window -t $selected_name -c $selected
        tmux new-window -t $selected_name -c $selected
        tmux send-keys -t $selected_name:1 'nvim .' Enter
        tmux send-keys -t $selected_name:3 'opencode' Enter
        tmux select-window -t $selected_name:1
fi

tmux switch-client -t $selected_name
